$path = 'module\talent.js'
$content = Get-Content $path -Raw
$descriptions = @{
  'air-of-authority' = 'The Explorer was born to command, either motivating or terrifying those under his charge. On a successful Command Test, the Explorer may affect a number of targets equal to 1d10 plus his Fellowship Bonus. This talent has no effect on hostile targets, and only affects NPCs.'
  'ambidextrous' = 'This Talent does not represent true ambidexterity so much as sufficient training with both hands to make the distinction moot. The Explorer can use either hand equally well for any task, and does not suffer the -20 penalty for actions using his off hand. Special: When combined with a Two-Weapon Wielder Talent, the penalty for making attacks with both weapons in the same Turn drops to -10.'
  'armour-of-contempt' = 'The Explorer''s hatred of all the impure armours his soul against malign influence. Whenever the Explorer gains Corruption Points, reduce the total by 1, to a minimum of 0. With a successful Willpower Test, taken as a Free Action, he may ignore the effects of accumulated Corruption Points for 1 Round.'
  'assassin-strike' = 'The Explorer''s natural agility and graceful martial forms turn him into a dervish of death on the battlefield. After making a melee attack, a successful Acrobatics Test allows him to move at half rate as a Free Action. The Explorer''s opponent does not receive a free attack resulting from this move. He may only take this additional move once per Round.'
  'autosanguine' = 'The ancient and blessed technology of the Mechanicus or some corrupt xeno tech flows through the Explorer''s blood. These miniscule machines repair minor injuries and speed healing. When applying healing, he is always considered Lightly Wounded, and heals at an increased rate, removing 2 points of Damage per day.'
  'bastion-of-iron-will' = 'The Explorer''s sheer willpower and psychic focus have become one and the same over years of practice and training, such that their combined use is second nature. He doubles his defensive Psy Rating on any Opposed Test involving the Psyniscience Skill or Psychic Techniques.'
  'battle-rage' = 'Long experience and indomitable will have allowed the Explorer to master the beast within, directing its rage while keeping a level head. He can Parry while Frenzied.'
  'berserk-charge' = 'The Explorer has learned to put the whole force of his momentum behind his weapon blows. When he charges into combat, few can stand before him. If he uses the Charge Action, he gains a +20 bonus to Weapon Skill instead of +10.'
  'binary-chatter' = 'The Explorer has optimised his use of Techna-Lingua for controlling servitors. He receives a +10 bonus to any attempt to communicate with servitors, and any vessel upon which he serves receives a +1 bonus to Crew Morale due to increased servitor efficiency.'
  'blademaster' = 'The Explorer''s mastery of bladed weapons and their martial disciplines has no peer. When attacking with any bladed weapon, including chain weapons, power axes, and power swords, he may re-roll one missed attack per Round.'
  'blessed-radiance' = 'The Explorer''s holiness shines out, allowing all to see the truth of their own souls. Where he treads, those who follow need have no fear of the darkness, nor suffer the predations of the blasphemous. When spending a Fate Point to activate the Pure Faith Talent, the Explorer extends the immunity to daemonic presence to a number of targets equal to twice his Willpower Bonus. As a free action, he may bestow a single Fate Point to an ally. If the Fate Point is unspent, it returns at the end of the encounter. Upon burning a Fate Point, the Explorer and a number of allies equal to twice his Willpower Bonus become immune to the effects of daemonic presence, Fear Tests, and Corruption Points. In addition, all affected targets gain a +10 bonus on Tests made to resist psychic attack or any other form of psychic manipulation. In addition, affected targets take only half Damage from psychic and warp sources. These benefits last for the duration of the encounter.'
  'blind-fighting' = 'Years of practice and development of the Explorer''s other senses allows him to fight in close combat without the benefit of sight. This Talent reduces all penalties for obscured vision by half, permitting the character to fight in fog, smoke, or darkness.'
  'bloodtracker' = 'The Explorer is an experienced and cunning bounty hunter who commands the highest price for bringing in a quarry in dead or alive. When turning in a fugitive for bounty, the character''s group gains a bonus of +100 Objective Points towards Military or Criminal Objectives.'
  'bulging-biceps' = 'Whereas a weaker man would be sent flying when using powerful weapons, the Explorer''s strong physique allows him to remain standing. He can fire heavy weapons using Semi-Auto Burst or Full Auto Burst without bracing, and he does not suffer the -30 penalty for failing to brace.'
  'catfall' = 'Gymnastic ability and natural balance enables the Explorer to fall far greater distances without harm than the common man. Whenever he falls, he may take an Agility Test as a Free Action. Success, and each additional Degree of Success, reduces the distance fallen by a number of metres equal to the character''s Agility Bonus for the purposes of determining the Damage from the fall.'
  'chem-geld' = 'Either chemical and surgical treatments or sheer will has rendered the Explorer immune to most mundane temptations. Seduction attempts against him automatically fail, and Charm Tests increase their Difficulty by one level. Taking this Talent causes one Insanity Point.'
  'cleanse-and-purify' = 'The Explorer can control the flow of molten promethium like no other, manipulating flame like an old accomplice. The targets of his flamer attacks take a -20 penalty their Agility Tests to escape its effects.'
  'combat-formation' = 'The Explorer has directed his comrades to be prepared for danger, planning out their actions for many contingencies if attacked. Before rolling initiative, all other members of the group may choose to use the character''s Intelligence Bonus for all initiative rolls rather than individual Agility Bonuses.'
  'combat-master' = 'The Explorer''s weapon seems to be everywhere at once, keeping many more opponents at bay in close combat than even skilled fighters. Opponents gain no bonuses for outnumbering the character in hand-to-hand combat.'
  'combat-sense' = 'The Explorer has the ability to consciously recognise the proddings of his subconscious as it reacts to his preternaturally sharp senses, giving the character an edge that mere speed cannot match. He can use his Perception Bonus in place of his Agility Bonus when rolling Initiative.'
  'concealed-cavity' = 'The character''s flesh or augmetics conceals a small compartment. This might be a pouch hidden under a flap of flesh, or a chamber fitted into a cybernetic enhancement. The Explorer may conceal one small item, no larger than a closed fist, within this cavity. Discovering this compartment requires success on a Difficult (-10) Search Test. If using a medicae scanner or auspex, the Difficulty is reduced to Ordinary (+10).'
  'counter-attack' = 'The Explorer''s lightning ripostes are things of beauty, if they were slow enough to be seen. After successfully Parrying an opponent''s attack, he may immediately make an attack against that opponent using the Parry weapon as a Free Action. This attack suffers a -20 penalty.'
  'crack-shot' = 'The Explorer can place his shots where they will inflict more harm: at creases, gaps, or joints in armour. When his ranged attack causes Critical Damage, add +2 to the Damage.'
  'crippling-strike' = 'The Explorer can land blows precisely where they will inflict the most harm, cutting into seams or hammering at weak points. When the character''s melee attack causes Critical Damage, add +4 Damage.'
  'crushing-blow' = 'The Explorer has the ability to focus his entire body into close combat attacks, adding +2 to damage inflicted in melee.'
  'dark-soul' = 'Prolonged exposure to darkness has acted as an inoculation against all that is foul, granting the Explorer resilience against corruption. Whenever he makes a Malignancy Test, he takes half the normal penalty.'
  'deadeye-shot' = 'The Explorer''s rock-steady hand and hawk-like eyesight make him a dreaded marksman. No target, however precise, can escape his crosshairs. When making a called shot, the character takes a -10 penalty instead of -20.'
  'die-hard' = 'Through either willpower or sheer stubbornness, the Explorer refuses to cross into shadow. When he suffers from blood loss, the character may roll twice to avoid death.'
  'disarm' = 'The Explorer can wrest weapons from an opponent''s hands through practiced technique or brute force. If in close combat, he may use a Full Action to disarm his foe by making an Opposed Weapon Skill Test. If he wins the Test, the opponent drops his weapon at his feet. If the character scores three or more Degrees of Success, he takes his opponent''s weapon.'
  'disturbing-voice' = 'The Explorer''s voice has particularly baleful or menacing qualities, causing others to quail before it. He gains +10 bonus to all Intimidate or Interrogation Tests when he employs this Talent, but suffers a -10 penalty to Fellowship Tests when dealing with others in a non-threatening manner, such as animals, children, or the easily startled.'
  'divine-ministration' = 'The Explorer is a vessel for the Emperor''s mercy and beneficence, his faith in his divinity can heal where no mere skill can. When testing Medicae, the Explorer may spend a Fate Point to restore an amount of Damage equal to his Willpower Bonus instead of the normal amount. This amount is then added to and multiplied in the normal way depending on the type of care. In the case of first aid to a Lightly Wounded character, the Explorer restores an amount of Damage equal to his Willpower Bonus plus his Intelligence Bonus. The Explorer may spend a Fate Point to remove all Fatigue from a number of people equal to twice his Willpower Bonus. The Explorer may burn a Fate Point to allow a character who has just died to have become Critically Wounded instead. This power has limits and is subject to the GM''s approval. If a use of Divine Ministration fails to work in this way, the Fate Point is not lost.'
}
foreach ($id in $descriptions.Keys) {
  $desc = ($descriptions[$id] -replace '\\', '\\' -replace '"', '\"')
  $pattern = 'id: "' + [regex]::Escape($id) + '",(?:(?!description:).)*?benefit: "(?:[^"\\]|\\.)*", category:'
  $content = [regex]::Replace($content, $pattern, {
    param($m)
    $m.Value.Replace(', category:', ', description: "' + $desc + '", category:')
  }, [System.Text.RegularExpressions.RegexOptions]::Singleline)
}
Set-Content $path $content

