$path = 'module\talent.js'
$content = Get-Content $path -Raw
$descriptions = @{
  'double-team' = 'The Explorer has the experience from many mass combats and swirling melees under his belt. When ganging up on an opponent, he gains an additional +10 bonus to Weapon Skill Tests. If both characters have this Talent, both gain an additional +10 bonus, for a total of +20. This bonus is in addition to the normal bonus gained from outnumbering opponents.'
  'dual-shot' = 'The Explorer''s skill with guns is such that he can target two shots on exactly the same point. When armed with two pistols, he can fire both simultaneously as a Full Action. Make a single Ballistic Skill Test, and if successful he hits his target with both shots. He does not suffer the normal -20 Ballistic Skill penalty for wielding two weapons. If he hits, the target''s Armour gets applied as normal to both hits individually, but Toughness only counts once against the combined Damage rolls of both hits. A single successful Dodge Test from the target will avoid both shots.'
  'dual-strike' = 'The Explorer''s skill with melee weapons can place two blows together to maximise damage. When armed with two melee weapons, he can attack with both simultaneously as a Full Action. Make a single Weapon Skill Test, and if successful, he hits the target with both weapons. He does not suffer the normal -20 Weapon Skill penalty for wielding two weapons. If he hits, the target''s Armour gets applied as normal to both hits individually, but Toughness only counts once against the combined Damage rolls of both hits. A single successful Dodge or Parry Test from the target will avoid both blows.'
  'duty-unto-death' = 'The Explorer''s will or faith can sustain him when his flesh is weak. He ignores the effects of injury, Fatigue, and Stunning during combat. This Talent does not prevent the Damage, but allows the character to temporarily ignore its effects for the duration of the combat. Death still affects him normally.'
  'electrical-succour' = 'The Explorer can channel the sacred flow of energy from his Potentia Coil or other energy source to replenish his flesh. Whilst in contact with a functioning, powered machine, or fully charged battery or power cell, the character may make an Ordinary (+10) Toughness Test. Success removes one level of Fatigue plus one additional level of Fatigue for each additional Degree of Success. This takes one minute of meditation and ritual incantation.'
  'electro-graft-use' = 'The Explorer may use his Electro Graft to access data ports and commune with machine spirits. This grants a +10 bonus to Common Lore, Inquiry, or Tech-Use Tests whilst connected to a data port.'
  'enemy' = 'The opposite of Good Reputation, the Explorer is particularly despised by a specific social group or organisation. He suffers an additional -10 penalty to Fellowship Tests when dealing with this group. This Talent is cumulative with the Rival Talent, for a total -20 penalty.'
  'energy-cache' = 'The Explorer has learned to focus the power stored within his Potentia Coil with greater efficiency. He no longer gains Fatigue from using Luminen Charge, Luminen Shock, and Luminen Blast.'
  'enhanced-bionic-frame' = 'The Explorer''s already impressive bionic body structure is steadied by a gyro-array guided by a targeting system linked to the machine-spirit. The Explorer gains the Auto-stabilised Trait.'
  'exotic-weapon-training' = 'The Explorer has received Exotic Weapon Training in a single Exotic Weapon, and can use it without penalty.'
  'favoured-by-the-warp' = 'Whenever a Focus Power Test results in Psychic Phenomena, the Explorer may roll twice on that table and take the more favourable result.'
  'fearless' = 'Through hard experience with horrifying situations, fear no longer commands the Explorer''s actions. He is immune to the effects of Fear and Pinning, but disengaging from combat or backing down from a fight requires a successful Willpower Test.'
  'feedback-screech' = 'The Explorer can haywire his vox synthesisers, causing a hideous blast of noise that shocks and distracts others. All unprotected creatures within a 30-metre radius who have the ability to hear must make a Willpower Test or lose a Half Action on their next Turn as they involuntarily react to the cacophonous shriek.'
  'ferric-lure' = 'The Explorer can cause an unsecured metal object within his field of vision to fly into his hand. The object may mass up to 1 kilogram per point of the character''s Willpower Bonus, and must lie within 20 metres. Using this Talent requires a Full Action and a successful Willpower Test.'
  'ferric-summons' = 'The Explorer can call an unsecured metal object to his hand as with Ferric Lure. But he may summon objects of up to 2 kilograms per point of his Willpower Bonus. The object may be up to 40 metres distant. The character must spend a Full Action and succeed on a Willpower Test to enact this rite.'
  'flame-weapon-training' = 'The sight of flaming streams of promethium brings joy to the Explorer''s heart and dread to his foes. He has mastered the art of a wide variety of flamer weapons. The Universal Talent group encompasses all non-Exotic weapons with the Flame special quality.'
  'foresight' = 'Logic and analysis do for the Explorer what Tarot and the bones claim to do for the superstitious masses. By careful consideration of all the possible consequences, and examination of all evidence and information, he can identify the best path for success. By spending ten minutes studying or analysing a problem, he gains a +10 bonus to his next Intelligence Test.'
  'frenzy' = 'The Explorer''s temper and passion boil just below the surface of his psyche, mostly held in check by his rational mind, but easily released when needed. If the character spends one full Round fuelling his anger, on the next Round he goes into an uncontrolled rage, gaining a +10 bonus to Weapon Skill, Strength, Toughness, and Willpower, but suffering a -20 penalty to Ballistic Skill and Intelligence. He must attack the nearest enemy in melee if possible. While Frenzied, he is immune to Fear, Pinning, stunning effects, the effects of Fatigue, and he may not Parry, retreat, or flee. He remains Frenzied for the duration of the combat.'
  'furious-assault' = 'The Explorer''s speed and martial prowess allow him to land several blows where lesser combatants land one. If he successfully hits his target using the All Out Attack Action, he may spend his Reaction to make an additional attack using the same bonuses or penalties as the original attack.'
  'guardian' = 'Years of serving as a bodyguard allow the Explorer to put himself in the line of fire, or to take a murderous attack that was intended for another. He may sacrifice all of his Actions for the next Round to switch places with an ally within 2 metres. This may be done at any time, even interrupting another action. The character become the target of any attacks previously targeting the ally. This Talent may not be used more than once per combat.'
  'gun-blessing' = 'Using the Explorer''s sacred ability to subtly affect ferrous materials, he can un-jam a number of weapons equal to his Intelligence Bonus, so long as they are within a 10-metre radius. A successful Intelligence Test indicates the character has appeased the spirits of the weapons. This blessing requires a Full Action.'
  'gunslinger' = 'The Explorer has trained with pistols for so long that they are like extensions of his own body, barely requiring conscious thought to aim and fire. When armed with two pistols, he reduces the penalty for Two-Weapon Fighting by -10. If he also possesses the Ambidextrous Talent, the penalty is reduced to 0.'
  'hard-bargain' = 'The Explorer''s shrewd negotiations and bartering skills are without peer, and he has a knack for seeing opportunities for profit where others see nothing. Whenever Profit Factor is awarded for completing an Endeavour, you gain a bonus of +1 Profit Factor to the group''s total.'
  'hard-target' = 'Light on his feet, the Explorer dodges and weaves as he moves, skills learned from long years in the line of fire. When he selects the Charge or Run Actions, opponents suffer a -20 penalty to Ballistic Skill Tests made to hit the character with a ranged weapon. This penalty continues until the start of the Explorer''s next Turn.'
  'hardy' = 'The Explorer''s constitution rebounds quickly from shock or injury. When undergoing medical treatment or healing from injuries, he recovers Damage as if Lightly Wounded.'
  'hatred' = 'A group, organisation or race has wronged the Explorer in the past, fuelling this animosity. When fighting opponents of that group in close combat, he gains a +10 bonus to all Weapon Skill Tests made against them.'
  'heavy-weapon-training' = 'The Explorer can employ some of the most devastating weapons of the battlefield. He can use weapons of the groups for which this Talent has been selected, choosing one new group each time. When a character attempts to use a weapon and he does not have the correct Weapon Training Talent for, he suffers a -20 penalty to any relevant Weapon Skill or Ballistic Skill Test.'
  'heightened-senses' = 'Either genetics or augmetics have made one of the Explorer''s senses superior to others. When he gains this Talent, select one of the five senses. The character gains a +10 bonus to any Tests specifically involving this sense.'
  'hip-shooting' = 'The Explorer''s prowess with ranged weapons is such that he can still fire accurately without using the sights. As a Full Action, the character may both move up to his Full Move rate and make a single attack with a ranged weapon. This attack can only be a single shot.'
  'hotshot-pilot' = 'The Explorer can pilot vehicles as if they were extensions of his own body. He may only select this Talent if he has obtained one Pilot Skill as an Advanced Skill. The character treats all other Pilot skills as Basic Skills, and receives a +10 bonus to the Pilot Skills he already possesses.'
  'infused-knowledge' = 'The Explorer has been infused with a great wealth of lore and knowledge, either through punishing noetic techniques or by arcane methods kept secret by the guardians of technology and knowledge. The Explorer treats all Common and Scholastic Lore Skills as untrained Basic Skills. This Talent also provides a +10 bonus to any Tests involving Common or Scholastic Lore for which he already possesses the Skill.'
  'improved-warp-sense' = 'The Explorer can now see the warp and physical universe side by side, no longer taking any concentration on his part. After gaining this Talent, the character may use the Psyniscience Skill as a Free Action.'
  'independent-targeting' = 'The Explorer has developed his peripheral vision and situational awareness to a point where he can fire in two directions within a split second. When firing two weapons as part of a single action, the targets need not be less than 10 metres apart.'
  'into-the-jaws-of-hell' = 'The Explorer inspires loyalty and devotion in his followers such that they would follow him into the warp or on a boarding action against xeno corsairs. In personal combat, while visible to them, they are immune to Fear and Pinning. While the character is known to be on board a ship in which he serves, the ship has a +5 bonus to its Morale.'
  'inspire-wrath' = 'The Explorer knows just the turn of phrase that incites individuals or groups to rage against others. His rhetoric grants +20 to Interaction Tests when inspiring hatred or anger, and double the number of individuals affected. This Talent can be combined with Master Orator to further increase the number of listeners affected.'
  'iron-discipline' = 'Iron sharpens iron. The Explorer does not coddle his crew, nor motivate them through kindness. His stalwart example and stern leadership exhorts them with steel instead of spoils. If the character is visible to his followers, either in person or via vox- or pict-caster, they may re-roll failed Willpower Tests made to resist Fear and Pinning. Iron Discipline can affect a number of targets equal to the character''s Willpower Bonus, who must be under his command.'
  'iron-jaw' = 'The Explorer has taken blows from Orks and given back as good as he got. He can bounce back from most strikes without ill effects. If ever Stunned, a successful Toughness Test allows him to ignore the effects.'
  'leap-up' = 'A combination of athletic ability and speed allow the Explorer to spring to his feet in virtually any circumstance. He may stand up as a Free Action.'
  'last-man-standing' = 'The Explorer has developed a sixth sense about hails of gunfire, allowing him to sense gaps and pauses in the lethal rain. He is immune to Pinning by Pistols and Basic Weapons, and adds +1 AP to the value of any cover protecting him from ranged attacks.'
  'light-sleeper' = 'The slightest change in conditions or disturbance brings the Explorer from sleep to full awareness, remaining alert even in slumber. He is always assumed to be awake, even when asleep, for the purposes of Awareness Tests or surprise.'
  'lightning-attack' = 'The Explorer''s speed with weapons is legendary, allowing him to launch flurries of attacks. As a Full Action, the character may make three melee attacks on his Turn. The effects of this Talent replace those of Swift Attack rather than adding to them.'
  'lightning-reflexes' = 'The Explorer always expects trouble, even in the most innocuous situations, allowing him to act quickly when needed. The character adds twice his Agility Bonus when rolling for Initiative. If he has Unnatural Agility, add +1 to the multiplier before factoring the bonus into the Initiative roll.'
  'litany-of-hate' = 'The Explorer''s belief in the righteousness of his hatred is so ingrained that he can rouse others to join his crusade. As a Full Action, the character may make a Charm Test to extend the effects of his Hatred Talent to any allies in the immediate vicinity. Success on the Test confers a +10 bonus to Weapon Skill when fighting hated foes to one target per point of the Explorer''s Fellowship Bonus. The effects last for the duration of the encounter.'
}
foreach ($id in $descriptions.Keys) {
  $desc = ($descriptions[$id] -replace '\\', '\\' -replace '"', '\"')
  $pattern = 'id: "' + [regex]::Escape($id) + '",(?:(?!description:).)*?benefit: "(?:[^"\\]|\\.)*", category:'
  $content = [regex]::Replace($content, $pattern, {
    param($m)
    $m.Value.Replace(', category:', ', description: "' + $desc + '", category:')
  }, [System.Text.RegularExpressions.RegexOptions]::Singleline)
}
Set-Content $path $content
