$path = 'module\talent.js'
$content = Get-Content $path -Raw
$descriptions = @{
  'logis-implant' = 'The Explorer may use analytical circuits to calculate trajectory and reactions to a preternatural extent. His ability to read possible outcomes lets him anticipate the movement of his opponents. By using his Reaction for the Round, the character may make a Tech-Use Test to make use of this Talent. He gains a +10 bonus to all Weapon Skill and Ballistic Skill Tests until the end of his next Turn. The Explorer must pass a Toughness Test when he uses this ability or gain a level of Fatigue.'
  'luminen-blast' = 'The Omnissiah has blessed the Explorer with augmetic conduits that parallel the bones of his arms. By reciting the proper litany, he can channel the energy stored in his Potentia Coil down these channels and direct it at his enemies. Success on a Ballistic Skill Test allows him direct this energy against a single target within 10 meters. The target takes 1d10 plus the Explorer''s Willpower Bonus in Energy Damage. The character must pass a Toughness Test when using this ability or gain a level of Fatigue. Talent Use: Half Action Attack.'
  'luminen-charge' = 'The Explorer has mastered the union between his holy mechanical elements and his mortal flesh, allowing the former to power the latter. With a successful Toughness Test the character may recharge or power machinery with his internal coils. This requires one minute of meditation and ritual incantation. The Explorer must pass a Toughness Test when he uses this ability or gain a level of Fatigue.'
  'luminen-shock' = 'The power of the Explorer''s Potentia Coil flows through a network of inductors within his flesh, allowing him to channel this energy into his blows. In close combat, a successful Weapon Skill Test or Grapple delivers the shock. The Luminen Shock inflicts 1d10+3 points of Energy Damage with the Shocking Quality. The Explorer must pass a Toughness Test when using this ability or gain a level of Fatigue. Talent Use: Half Action Attack.'
  'machinator-array' = 'The Explorer has returned to the creches of the Mechanicus so they can bring him closer to the most holy of forms, adding an extensive machinator array to his existing augmetics. The Explorer''s Strength and Toughness Characteristics are increased by +10, and his Agility and Fellowship are reduced by -5. His mass increases to three times that of a normal person, and he may no longer stay afloat or swim in water or similar liquids. The character may mount a single pistol type or close combat weapon on any Ballistic Mechadendrites he possesses. He must still have the proper Talent to use the mounted weapon.'
  'maglev-grace' = 'The Explorer stitches augmetic coils throughout the systems or flesh of his legs, granting him the ability to float a short distance above the ground. Using a Half Action, the character may hover 20 to 30 centimetres off the ground for a number of minutes equal to 1d10 plus his Toughness Bonus. The Explorer must employ a Half Action each round to maintain the rite, and may use the other actions to move normally. He may activate this rite to slow his rate of descent when falling, reducing all falling Damage to 1d10+3 Impact. Each use of Maglev Grace exhausts the power stored in the Potentia Coil.'
  'maglev-transcendence' = 'The Explorer has proven his devotion to the Machine God by lacing augmetic coils through every portion of his body. Using a Half Action, he may hover 20 to 30 centimetres off the ground for a number of minutes equal to 2d10 plus his Toughness Bonus. He may move up to his running speed while maintaining the rite. He can slow his rate of descent when falling so long as this rite is active when he reaches the ground, taking no falling damage. Each time he enacts this rite, it drains 50% of his Potentia Coil.'
  'marksman' = 'The Explorer''s steady hand and eagle eye allows him to keep crosshairs steady on any target, regardless of range. Distance is no protection against his fire. The Explorer suffers no penalties for Ballistic Skill Tests at long or extended range.'
  'master-and-commander' = 'There can be only one commander of a vessel, and the Explorer''s guiding hand, stern judgment, and sage leadership have captained his crew through countless conflicts. By spending a Half Action in combat to direct the efforts of his allies, none of them suffer the penalties for ganging up until his next Turn. If defending against a boarding action, a Half Action directs the efforts of his armsmen, granting them a +10 bonus in combat.'
  'master-chirurgeon' = 'The Explorer''s advanced medical skills enable him knit flesh with deft mastery. His exceptional education in use of the Narthecium, Med-Slate, and supplemental drugs gives his patients an enormous advantage. The Explorer gains a +10 bonus on all Medicae Tests. If treating a Heavily or Critically Wounded patient, a successful Test heals 2 points of Damage instead of 1. If the patient is in danger of losing a limb from a Critical Hit, the Explorer provides him with a +20 bonus to the Toughness Test to prevent limb loss.'
  'master-enginseer' = 'The Explorer''s knowledge of starships and their machine spirits surpasses all his planet-bound brethren. The character can almost feel the plasma pulsing through the ship''s conduits as if it were his own veins. He may spend a Fate Point for automatic success on a Tech-Use Test for enhancement, repair, or upgrade of starship systems, taking the minimum amount of time possible on the task.'
  'master-orator' = 'The Explorer has learned the techniques required to influence large audiences. His Fellowship Tests and Fellowship-based Skill Tests affect 10 times the normal number of targets.'
  'mechadendrite-use' = 'Though there are many different types of Mechadendrite, this Talent divides them into two broad categories: Weapon, for mechadendrites ending in ranged or close combat weapons with the support and strength necessary for combat; and Utility, for machine spirit interface, manipulator, medicae, optical, and similar varieties that interface with the cyber mantle in a similar manner.'
  'meditation' = 'The Explorer has mastered his body and its reactions by prayer to the Emperor, shutting down unnecessary functions to refresh his body and mind. Success on a Willpower Test and 10 minutes without interruptions removes one level of Fatigue.'
  'mighty-shot' = 'The Explorer knows the weak points in every armour and material, and has the skill to place shots exactly where they will do the most damage. He adds +2 to Damage with a ranged weapon.'
  'mimic' = 'Vox synthesisers, training or innate abilities allow the Explorer to accurately mimic the voice of another. He must study the voice patterns of his target for at least one hour for proper imitation, and speak the same language. Listeners must succeed on a Difficult (-10) Scrutiny Test to penetrate the deception. If the character studies used vox recordings or comm-link conversations rather than in-person observation, the Difficulty of the Scrutiny Test is reduced to Challenging (+0). His deception automatically fails if the listener can clearly see he is not the imitated individual.'
  'navigator' = 'The Explorer was born with the Navigator gene, either of the Navis Nobilite or in the shadowed ranks of the unlicensed. The Warp Eye stares balefully from his forehead, allowing him to perceive the ebbs and flows of the empyrean. For more details, see Navigator Powers.'
  'navigator-power' = 'The Explorer''s trainers or natural ability allows use of an additional Navigator Power. This Talent may be chosen multiple times, each selection granting a new Power.'
  'nerves-of-steel' = 'Long years on the battlefield enable the Explorer to remain calm as fire impacts all around. He may re-roll failed Willpower Tests to avoid or recover from Pinning.'
  'orthoproxy' = 'A liturgical circuit has been implanted within the Explorer''s skull, allowing him to focus on the prayers recited by the proxy unit when his mental fortitude is in peril. He receives a +20 bonus to Willpower Tests made to resist mind control or interrogation.'
  'paranoia' = 'The Explorer knows that danger lurks behind every corner and knows the galaxy will hit him as soon as he lets his guard down. The character gains a +2 bonus on Initiative rolls, and the GM may secretly Test his Perception to notice hidden threats. The price of his eternal vigilance is a twitchy disposition and the inability to relax.'
  'pistol-weapon-training' = 'The Explorer has practiced with nearly every single-handed ranged weapon within the confines of the Imperium, and no small number without. The Universal group confers proficiency with most pistol weapons, including the Bolt, Las, Launcher, Melta, Plasma, and SP groups. When a character attempts to use a weapon he does not have the correct Weapon Training Talent for, he suffers a -20 penalty to any relevant Weapon Skill or Ballistic Skill Test.'
  'polyglot' = 'The Explorer has an innate ability to derive meaning from unknown languages and make himself understood using this intuitive grasp. He treats all languages as Basic Skills. This is not the same as true knowledge of the language, and tests using this Talent suffer a -10 penalty due to the simplistic nature of translation.'
  'precise-blow' = 'The Explorer''s eye, hand, and weapon act seamlessly together, placing blows exactly where the attacker intends. When making a called shot with a melee weapon, the Explorer does not incur the -20 penalty.'
  'prosanguine' = 'Through the Explorer''s iron will or via appeals to the Omnissiah, he is able to speed the function of his Autosanguinators. By spending 10 minutes in meditation and ritual incantation, the character may make a Tech-Use Test, and if successful, remove 1d5 points of Damage. If he rolls a 96-100, he overstrains his implants, losing the ability to use them for one week. During that week, the Explorer may use neither the Autosanguine nor Prosanguine Talents.'
  'psy-rating' = 'The Explorer is a psyker, and his power in game terms is rated on a scale of 1 to 10. Increasing a character''s Psy Rating represents that character unlocking more of his psychic potential and becoming more powerful. An Explorer can take this Talent multiple times; each time it is taken, his current Psy Rating increases by 1.'
  'psychic-discipline' = 'The Explorer gains access to a new Psychic Discipline, and may select techniques from this new field of study as his abilities increase. Psykers may access a maximum of three separate Disciplines.'
  'psychic-technique' = 'Either through training or natural development, the Explorer has learned an additional Psychic Technique. Once this Talent has been selected, the Explorer may select one new Psychic Technique in any Discipline he possesses with an xp cost equal to or lower than the Talent''s xp cost. This Talent may be chosen multiple times, each selection granting an additional Technique.'
  'pure-faith' = 'The Explorer''s faith in the God Emperor of Mankind, his divine power and grace, is total and complete. Pure Faith provides all of the following benefits: the Explorer is always immune to the effects of Daemonic Presence, including negative modifiers to Willpower; by spending a Fate Point he may avoid Fear Tests, Insanity Points, and Corruption Points for the duration of the encounter; and by burning a Fate Point he may resist the effects of any single daemonic or psychic attack, emerging unscathed as if by a miracle.'
  'purge-the-unclean' = 'The Explorer can focus his faith through words, gestures, and force of will such that a daemon may be cowed or cast out by the power of the Emperor. As a half action he may spend a Fate Point to repel a warp entity. As a full action he may spend a Fate Point to force out a possessing warp entity from its host. As a full action he may burn a Fate Point to chant the litanies of detestation to purge a warp entity from reality, dealing direct harm not reduced by Toughness or Armour.'
}
foreach ($id in $descriptions.Keys) {
  $desc = ($descriptions[$id] -replace '\\', '\\' -replace '"', '\"')
  $pattern = 'id: "' + [regex]::Escape($id) + '",(?:(?!description:).)*?benefit: "(?:[^"\\]|\\.)*", category:'
  $content = [regex]::Replace($content, $pattern, {
    param($m)
    $m.Value.Replace(', category:', ', description: "' + $desc + '", category:')
  }, [System.Text.RegularExpressions.RegexOptions]::Singleline)
}
Set-Content $path $content
